apiVersion: apps/v1
kind: Deployment
metadata:
  name: minuevaappp1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: minuevaapp1
  template:
    metadata:
      labels:
        app: minuevaapp1
    spec:
      containers:
      - name: midocker
        image: mi_docker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.service.port }}
